FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Используем shell-формат для CMD, чтобы избежать проблем с интерпретацией
CMD python main.py
